### ISSUE TITLE
cursor pointer not available

### ISSUE THREAD

**Issue by itsNikolay** [rnicholus/file-input#30]
can not set `cursor: pointer;` to `file-input`

```
<file-input>
  <paper-button><paper-button>
  <core-icon></core-icon>
</file-input>
```

and css

``` css
file-input { cursor: pointer }
```

has no effect
